application: kanyorien
version: 1
runtime: python
api_version: 1

handlers:

- url: /fetch_and_post_material
  script: app.py
  login: admin

- url: /update_users
  script: app.py
  login: admin

- url: /.*
  script: app.py
